const { test } = require('@playwright/test')
const { callStoryId } = require('../uib-components/.utils/playwright/pw-story-call')

test.describe('GUI', () => {
  // TODO: Default layout with client page
  test.describe('Main layout', () => {})
  // test.describe('Page content', () => {
  //   test('breadcrumb', async ({ page }) => {
  //     await callStoryId(page, 'bar-b-breadcrumb', 'b-breadcrumb')
  //     const component = await page.locator('[data-testid="BarBBreadcrumb"]')
  //     await component.evaluate(() => { document.querySelector('.breadcrumb').innerHTML = 'Server / Configuration' })
  //     await component.screenshot({ path: './screenshots/en/opsiweb_breadcrumb.png' })
  //     await component.evaluate(() => { document.querySelector('.breadcrumb').innerHTML = 'Server / Konfiguration' })
  //     await component.screenshot({ path: './screenshots/de/opsiweb_breadcrumb.png' })
  //   })
  //   test('header', async ({ page }) => {
  //     await callStoryId(page, 'bar-b-collapse-page-header', 'b-collapse-page-header')
  //     const component = await page.locator('[data-testid="BarBCollapsePageHeader"]')
  //     await component.evaluate(() => { document.querySelector('.nav-title').innerHTML = 'Clients' })
  //     await component.evaluate(() => { document.querySelector('.tableheader_depots').innerHTML = 'Server' })
  //     await component.evaluate(() => { document.querySelector('.tableheader_hostgroup').innerHTML = 'Hostgroups' })
  //     await component.evaluate(() => { document.querySelector('.tableheader_products').innerHTML = 'Products' })
  //     await component.screenshot({ path: './screenshots/en/opsiweb_header.png' })
  //     await component.evaluate(() => { document.querySelector('.tableheader_hostgroup').innerHTML = 'Hostgruppen' })
  //     await component.evaluate(() => { document.querySelector('.tableheader_products').innerHTML = 'Produkte' })
  //     await component.screenshot({ path: './screenshots/de/opsiweb_header.png' })
  //   })
  // })
  // test.describe('Table', () => {
  //   test('filter', async ({ page }) => {
  //     await callStoryId(page, 'input-i-filter', 'i-filter')
  //     const component = await page.locator('[data-testid="IFilter"]')
  //     await component.type('Filter ID')
  //     await component.screenshot({ path: './screenshots/en/opsiweb_table_filter.png' })
  //     await component.screenshot({ path: './screenshots/de/opsiweb_table_filter.png' })
  //   })
  //   test('sorting', async ({ page }) => {
  //     await callStoryId(page, 'dropdown-dd-table-sorting', 'dd-table-sorting')
  //     await page.click('[data-testid="DropdownDDTableSorting"] .btn')
  //     await page.setViewportSize({ width: 220, height: 310 })
  //     const component = await page.locator('[data-testid="DropdownDDTableSorting"]')
  //     await component.evaluate(() => { document.querySelector('.sortDirection').innerHTML = 'Sort descending' })
  //     await page.screenshot({ path: './screenshots/en/opsiweb_table_sorting.png' })
  //     await component.evaluate(() => { document.querySelector('.sortDirection').innerHTML = 'Absteigende Sortierung' })
  //     await page.screenshot({ path: './screenshots/de/opsiweb_table_sorting.png' })
  //   })
  //   test('column selection', async ({ page }) => {
  //     await callStoryId(page, 'dropdown-dd-table-column-visibility', 'dd-table-column-visibility')
  //     await page.click('[data-testid="DropdownDDTableColumnVisibility"] .btn')
  //     await page.setViewportSize({ width: 220, height: 210 })
  //     await page.screenshot({ path: './screenshots/en/opsiweb_table_columnselection.png' })
  //     await page.screenshot({ path: './screenshots/de/opsiweb_table_columnselection.png' })
  //   })
  //   test('pagination', async ({ page }) => {
  //     await callStoryId(page, 'bar-b-table-footer', 'b-table-footer')
  //     const component = await page.locator('[data-testid="BTableFooter"]')
  //     await component.screenshot({ path: './screenshots/en/opsiweb_table_pagination.png' })
  //     await component.screenshot({ path: './screenshots/de/opsiweb_table_pagination.png' })
  //   })
  // })
})
// test.describe('Quick Start', () => {
//   test('Login', async ({ page }) => {
//     await callStoryId(page, 'form-f-login', 'f-login')
//     const component = await page.locator('[data-testid="FLogin"]')
//     await component.evaluate(() => { document.querySelector('.projectTitle').innerHTML = 'OPSIWEB' })
//     await component.evaluate(() => { document.querySelector('.username').placeholder = 'Username' })
//     await component.evaluate(() => { document.querySelector('.password').placeholder = 'Password' })
//     await component.evaluate(() => { document.querySelector('.login').innerHTML = 'Login' })
//     await component.screenshot({ path: './screenshots/en/opsiweb_login.png' })
//     await component.evaluate(() => { document.querySelector('.username').placeholder = 'Benutzername' })
//     await component.evaluate(() => { document.querySelector('.password').placeholder = 'Passwort' })
//     await component.evaluate(() => { document.querySelector('.login').innerHTML = 'Anmeldung' })
//     await component.screenshot({ path: './screenshots/de/opsiweb_login.png' })
//   })
//   test('Client creation', async ({ page }) => {
//     await callStoryId(page, 'view-v-clients-add-new', 'v-clients-add-new')
//     const component = await page.locator('[data-testid="VClientsAddNew"]')
//     await component.evaluate(() => { document.querySelector('.id').innerHTML = 'ID' })
//     await component.evaluate(() => { document.querySelector('.domainName').placeholder = '.domain.local' })
//     await component.evaluate(() => { document.querySelector('.clientDetails').innerHTML = 'Client Details:' })
//     await component.evaluate(() => { document.querySelector('.description').innerHTML = 'Description' })
//     await component.evaluate(() => { document.querySelector('.inventNum').innerHTML = 'Inventory Number' })
//     await component.evaluate(() => { document.querySelector('.hwAddr').innerHTML = 'MAC' })
//     await component.evaluate(() => { document.querySelector('.ip').innerHTML = 'IP' })
//     await component.evaluate(() => { document.querySelector('.addtnlInfo').innerHTML = 'Additional Information:' })
//     await component.evaluate(() => { document.querySelector('.notes').innerHTML = 'Notes' })
//     await component.evaluate(() => { document.querySelector('.uefi').innerHTML = 'UEFI' })
//     await component.evaluate(() => { document.querySelector('.resetButton').innerHTML = 'Reset' })
//     await component.evaluate(() => { document.querySelector('.addButton').innerHTML = 'Add' })
//     await component.screenshot({ path: './screenshots/en/opsiweb_clientcreation.png' })
//     await component.evaluate(() => { document.querySelector('.description').innerHTML = 'Beschreibung' })
//     await component.evaluate(() => { document.querySelector('.inventNum').innerHTML = 'Inventar Nummer' })
//     await component.evaluate(() => { document.querySelector('.addtnlInfo').innerHTML = 'Zusätzliche Information:' })
//     await component.evaluate(() => { document.querySelector('.notes').innerHTML = 'Anmerkungen' })
//     await component.evaluate(() => { document.querySelector('.resetButton').innerHTML = 'Zurücksetzen' })
//     await component.evaluate(() => { document.querySelector('.addButton').innerHTML = 'Hinzufügen' })
//     await component.screenshot({ path: './screenshots/de/opsiweb_clientcreation.png' })
//   })
// })
test.describe('Manage', () => {
  // test('Servers', async ({ page }) => {
  //   await callStoryId(page, 'view-v-depots', 'v-depots')
  //   const component = await page.locator('[data-testid="VDepots"]')
  //   await component.evaluate(() => { document.querySelector('.nav-title').innerHTML = 'Servers' })
  //   await component.evaluate(() => { document.querySelector('.count').innerHTML = '1/7' })
  //   await component.evaluate(() => { document.querySelector('.filter').placeholder = 'Filter ID' })
  //   await component.screenshot({ path: './screenshots/en/opsiweb_servers.png' })
  //   await component.screenshot({ path: './screenshots/de/opsiweb_servers.png' })
  // })
  // test('Clients', async ({ page }) => {
  //   await callStoryId(page, 'view-v-clients', 'v-clients')
  //   const component = await page.locator('[data-testid="VClients"]')
  //   await component.evaluate(() => { document.querySelector('.nav-title').innerHTML = 'Clients' })
  //   await component.evaluate(() => { document.querySelector('.tableheader_depots').innerHTML = 'Server' })
  //   await component.evaluate(() => { document.querySelector('.tableheader_hostgroup').innerHTML = 'Hostgroups' })
  //   await component.evaluate(() => { document.querySelector('.tableheader_products').innerHTML = 'Products' })
  //   await component.evaluate(() => { document.querySelector('.count').innerHTML = '0/5' })
  //   await component.evaluate(() => { document.querySelector('.filter').placeholder = 'Filter ID' })
  //   await component.screenshot({ path: './screenshots/en/opsiweb_clients.png' })
  //   await component.evaluate(() => { document.querySelector('.tableheader_hostgroup').innerHTML = 'Hostgruppen' })
  //   await component.evaluate(() => { document.querySelector('.tableheader_products').innerHTML = 'Produkte' })
  //   await component.screenshot({ path: './screenshots/de/opsiweb_clients.png' })
  // })
  // test('Products', async ({ page }) => {
  //   await callStoryId(page, 'view-v-products', 'v-products')
  //   const component = await page.locator('[data-testid="VProducts"]')
  //   await component.evaluate(() => { document.querySelector('.nav-title').innerHTML = 'Products' })
  //   await component.evaluate(() => { document.querySelector('.tableheader_depots').innerText = 'Server' })
  //   await component.evaluate(() => { document.querySelector('.tableheader_hostgroup').innerText = 'Hostgroups' })
  //   await component.evaluate(() => { document.querySelector('.tableheader_productgroup').innerText = 'Productgroups' })
  //   await component.evaluate(() => { document.querySelector('.count').innerHTML = '0/3' })
  //   await component.evaluate(() => { document.querySelector('.localboot').innerHTML = 'Localboot(3)' })
  //   await component.evaluate(() => { document.querySelector('.netboot').innerHTML = 'Netboot(7)' })
  //   await component.evaluate(() => { document.querySelector('.filter').placeholder = 'Filter ID' })
  //   await component.screenshot({ path: './screenshots/en/opsiweb_products.png' })
  //   await component.evaluate(() => { document.querySelector('.nav-title').innerHTML = 'Produkte' })
  //   await component.evaluate(() => { document.querySelector('.tableheader_hostgroup').innerText = 'Hostgruppen' })
  //   await component.evaluate(() => { document.querySelector('.tableheader_productgroup').innerText = 'Produktgruppen' })
  //   await component.screenshot({ path: './screenshots/de/opsiweb_products.png' })
  // })
  // test('HostGroups', async ({ page }) => {
  //   await callStoryId(page, 'tree-ts-host-groups', 'ts-host-groups')
  //   await page.click('[data-testid="TSHostGroups"]')
  //   const component = await page.locator('[data-testid="TSHostGroups"]')
  //   await component.evaluate(() => { document.querySelector('.vue-treeselect__placeholder').innerHTML = 'Hostgroups' })
  //   await component.evaluate(() => { document.querySelector('.clearButton').innerHTML = 'Clear selection' })
  //   await page.setViewportSize({ width: 320, height: 210 })
  //   await page.screenshot({ path: './screenshots/en/opsiweb_hostgroups.png' })
  //   await component.evaluate(() => { document.querySelector('.vue-treeselect__placeholder').innerHTML = 'Hostgruppen' })
  //   await component.evaluate(() => { document.querySelector('.clearButton').innerHTML = 'Markierungen entfernen' })
  //   await page.screenshot({ path: './screenshots/de/opsiweb_hostgroups.png' })
  // })
  test('ProductGroups', async ({ page }) => {
    await callStoryId(page, 'tree-ts-product-groups', 'ts-product-group')
    await page.click('[data-testid="TSProductGroups"]')
    const component = await page.locator('[data-testid="TSProductGroups"]')
    await component.evaluate(() => { document.querySelector('.vue-treeselect__placeholder').innerHTML = 'Productgroups' })
    await component.evaluate(() => { document.querySelector('.clearButton').innerHTML = 'Clear selection' })
    await page.setViewportSize({ width: 320, height: 210 })
    await page.screenshot({ path: './screenshots/en/opsiweb_productgroups.png' })
    await component.evaluate(() => { document.querySelector('.vue-treeselect__placeholder').innerHTML = 'Produktgruppen' })
    await component.evaluate(() => { document.querySelector('.clearButton').innerHTML = 'Markierungen entfernen' })
    await page.screenshot({ path: './screenshots/de/opsiweb_productgroups.png' })
  })
  // test('Host attributes', async () => {})
  // test('Client deletion', async () => {})
  // test('Client reboot', async () => {})
  // test('Client logs', async () => {})
  // test('Properties and Dependencies', async () => {})
  // test('Quick Save', async ({ page }) => {
  //   await callStoryId(page, 'view-v-settings-local-specific', 'v-settings-local-specific')
  //   const component = await page.locator('[data-testid="VSettingsLocalSpecific"]')
  //   await page.setViewportSize({ width: 420, height: 100 })
  //   await component.evaluate(() => { document.querySelector('.quicksave').innerHTML = 'Quick save' })
  //   await component.screenshot({ path: './screenshots/en/opsiweb_quicksave.png' })
  //   await component.evaluate(() => { document.querySelector('.quicksave').innerHTML = 'Sofort speichern' })
  //   await component.screenshot({ path: './screenshots/de/opsiweb_quicksave.png' })
  // })
  // test('Push installations', async () => {})
  // test('Selections', async () => {})
})
// test.describe('OPSI specific Settings', () => {
//   // TODO: Settings page with Modules content selected
//   test('OPSI Modules', async ({ page }) => {
//     await callStoryId(page, 'view-v-modules', 'v-modules')
//     const component = await page.locator('[data-testid="VModules"]')
//     await component.evaluate(() => { document.querySelector('.modules').innerHTML = 'Available modules' })
//     await component.screenshot({ path: './screenshots/en/opsiweb_opsiModules.png' })
//     await component.evaluate(() => { document.querySelector('.modules').innerHTML = 'Verfügbare Module' })
//     await component.screenshot({ path: './screenshots/de/opsiweb_opsiModules.png' })
//   })
// })
// test.describe('GUI Settings', () => {
//   test('Language', async ({ page }) => {
//     await callStoryId(page, 'dropdown-dd-lang', 'dd-lang')
//     const component = await page.locator('[data-testid="DropdownDDLang"]')
//     await component.click()
//     await page.setViewportSize({ width: 220, height: 150 })
//     await page.screenshot({ path: './screenshots/en/opsiweb_language.png' })
//     await page.screenshot({ path: './screenshots/de/opsiweb_language.png' })
//   })
//   test('Theme', async ({ page }) => {
// TODO: Main layout in dark theme
//     await callStoryId(page, 'dropdown-dd-theme', 'dd-theme')
//     await page.click('[data-testid="DropdownDDTheme"] .btn')
//     await page.setViewportSize({ width: 220, height: 150 })
//     await page.screenshot({ path: './screenshots/en/opsiweb_theme.png' })
//     await page.screenshot({ path: './screenshots/de/opsiweb_theme.png' })
//   })
// })
