/**
This file is part of opsi-webgui application.
opsi-webgui is part of the desktop management solution opsi http://www.opsi.org
Copyright (c) uib GmbH <info@uib.de> 2025
All rights reserved.
License: AGPL-3.0
*/
export const useIcons = () => {
  // All available icons: https://icon-sets.iconify.design
  // prefered urrently: bootstrap icons
  const icon = {
    depots: 'bi:server',
    client: 'bi:laptop',
    product: 'bi:box-seam',
    group: 'bi:diagram-2',
    admin: 'bi:tools',
    support: 'bi:headset',
    settings: 'bi:gear',
    language: 'bi:globe2',
    logout: 'bi:power',
    themelight: 'bi:sun',
    themedark: 'bi:moon',
    trackChanges: 'bi:card-checklist',
    toggleVisibilityLeft: 'bi:chevron-bar-left',
    toggleVisibilityRight: 'bi:chevron-bar-right',
    tree: 'bi:list-nested',
    table: 'bi:table',
    navmenu: 'bi:list',
    menu: 'bi:three-dots-vertical',
    quickpanel: 'bi:grid',
    loading: 'eos-icons:three-dots-loading',
    // loading: 'bi:three-dots',
    refetch: 'bi:arrow-clockwise',
    rename: 'bi:pencil-square',
    reset: 'bi:arrow-counterclockwise',
    exclamation: 'bi:exclamation',
    warning: 'bi:exclamation-triangle',
    copy: 'bi:copy',
    edit: 'bi:pencil',
    x: 'bi:x',
    add: 'bi:plus',
    delete: 'bi:trash',
    help: 'bi:question-circle',
    info: 'bi:info-circle',
    infoselections: 'bi:info-circle',
    download: 'bi:download',
    check: 'bi:check2',
    checkBox: 'material-symbols:check-box-outline',
    dash: 'bi:dash',
    valueShow: 'bi:eye-slash',
    valueHide: 'bi:eye',
    arrowRight: 'bi:chevron-right',
    arrowLeft: 'bi:chevron-left',
    arrowUp: 'bi:chevron-up',
    arrowDown: 'bi:chevron-down',
    arrowDoubleUp: 'bi:chevron-double-up',
    arrowDoubleDown: 'bi:chevron-double-down',
    arrowDoubleLeft: 'bi:chevron-double-left',
    arrowDoubleRight: 'bi:chevron-double-right',
    arrowFillUp: 'bi:caret-up',
    arrowFillDown: 'bi:caret-down-fill',
    log: 'bi:file-earmark-text',
    clientReachable: 'bi:link-45deg',
    onDemand: 'bi:collection-play',
    deployClientAgent: 'material-symbols-light:real-estate-agent-outline-sharp',
    notify: 'bi:envelope',
    reboot: 'bi:bootstrap-reboot',
    productInstallationStatusInstalled: 'material-symbols-light:install-desktop-rounded',
    productInstallationStatusUnknown: 'bi:question',
    productActionResult: 'bi:hourglass-bottom',
    productsFailedActionResult: 'bi:exclamation',
    productActionResultSuccessful: 'bi:check',
    productsOutdatedLocal: 'material-symbols-light:deployed-code-history-outline-rounded',
    productsOutdatedNet: 'material-symbols-light:deployed-code-history-rounded',
    sort: 'bi:arrows-vertical',
    sortAsc: 'bi:sort-up',
    sortDesc: 'bi:sort-down',
    columns: 'bi:grid-3x3',
    filter: 'bi:funnel',
    clear: 'bi:brush',
    refresh: 'bi:arrow-repeat',
    readonly: 'material-symbols-light:edit-off-outline',
    unequal: 'mdi:not-equal-variant',
    bookmark: 'bi:bookmark-fill',
  }
  return { ...icon }
}
