/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PBadge: typeof import('primevue/badge')['default']
    PButton: typeof import('primevue/button')['default']
    PCheckbox: typeof import('primevue/checkbox')['default']
    PColumn: typeof import('primevue/column')['default']
    PDialog: typeof import('primevue/dialog')['default']
    PFloatLabel: typeof import('primevue/floatlabel')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PMultiSelect: typeof import('primevue/multiselect')['default']
    PPopover: typeof import('primevue/popover')['default']
    PSelect: typeof import('primevue/select')['default']
    PTag: typeof import('primevue/tag')['default']
    PToggleSwitch: typeof import('primevue/toggleswitch')['default']
    PTreeTable: typeof import('primevue/treetable')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
