// const defaultTheme = require('tailwindcss/defaultTheme')
// const
export default {
  content: [
    './components/**/*.{vue,js,ts,tsx}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts,tsx}',
    './nuxt.config.{js,ts}',
  ],
  theme: {
    extend: {
      colors: {
        'opsi-magenta': 'var(--color-opsi-magenta)',
        'opsi-deep-blue': 'var(--color-opsi-deep-blue)',
        'opsi-blue': 'var(--color-opsi-blue)',
        'opsi-deep-gray': 'var(--color-opsi-deep-gray)',
        'opsi-gray': 'var(--color-opsi-gray)',
        'opsi-medium-gray': 'var(--color-opsi-medium-gray)',
        'opsi-light-gray': 'var(--color-opsi-light-gray)',
        'opsi-base-light-background': 'var(--color-opsi-base-light-background)',
        'opsi-base-light-text': 'var(--color-opsi-base-light-text)',
        'opsi-base-dark-background': 'var(--color-opsi-base-dark-background)',
        'opsi-base-dark-text': 'var(--color-opsi-base-dark-text)',
        'opsi-log-light-secret': 'var(--color-opsi-log-light-secret)',
        'opsi-log-light-trace': 'var(--color-opsi-log-light-trace)',
        'opsi-log-light-debug': 'var(--color-opsi-log-light-debug)',
        'opsi-log-light-info': 'var(--color-opsi-log-light-info)',
        'opsi-log-light-notice': 'var(--color-opsi-log-light-notice)',
        'opsi-log-light-warning': 'var(--color-opsi-log-light-warning)',
        'opsi-log-light-error': 'var(--color-opsi-log-light-error)',
        'opsi-log-light-critical': 'var(--color-opsi-log-light-critical)',
        'opsi-log-light-essential': 'var(--color-opsi-log-light-essential)',
        'opsi-log-dark-secret': 'var(--color-opsi-log-dark-secret)',
        'opsi-log-dark-trace': 'var(--color-opsi-log-dark-trace)',
        'opsi-log-dark-debug': 'var(--color-opsi-log-dark-debug)',
        'opsi-log-dark-info': 'var(--color-opsi-log-dark-info)',
        'opsi-log-dark-notice': 'var(--color-opsi-log-dark-notice)',
        'opsi-log-dark-warning': 'var(--color-opsi-log-dark-warning)',
        'opsi-log-dark-error': 'var(--color-opsi-log-dark-error)',
        'opsi-log-dark-critical': 'var(--color-opsi-log-dark-critical)',
        'opsi-log-dark-essential': 'var(--color-opsi-log-dark-essential)',
        'opsi-ok': 'var(--color-opsi-ok)',
        'opsi-ok-dark': 'var(--color-opsi-ok-dark)',
        'opsi-warning': 'var(--color-opsi-warning)',
        'opsi-warning-dark': 'var(--color-opsi-warning-dark)',
        'opsi-error': 'var(--color-opsi-error)',
        'opsi-error-dark': 'var(--color-opsi-error-dark)',
      },

      width: {
        '1/1': '100%',
        '1/2': '50%',
        '1/3': '33.333333%',
        '2/3': '66.666667%',
      },
      minWidth: {
        '1/1': '100%',
        '1/2': '50%',
        '1/3': '33.333333%',
        '2/3': '66.666667%',
      },
      maxWidth: {
        '1/1': '100%',
        '1/2': '50%',
        '1/3': '33.333333%',
        '2/3': '66.666667%',
      },
      minHeight: {
        '1/4': '25vh',
        '1/2': '50vh',
        '3/4': '75vh',
        '192': '48rem',
      },
      height: {
        '128': '32rem',
        '192': '48rem',
      },
      fontFamily: {
        // usage by class 'font-logo' etc. or update tailwind.css to set font for specific tags
        'logo': ['MontserratAlt1', 'sans-serif'],
        'heading': ['Montserrat', 'sans-serif'],
        'sans': ['OpenSans', 'sans-serif'],
        'mono': ['DroidSansMono', 'monospace'],
      },
    },
  },
  plugins: [],
}