version: '3.8'

include:
  - path: ./opsi-docker/opsi-server/docker-compose-env.yml
    env_file:
      # - .devcontainer/opsi-docker/opsi-server/opsi-server.env
      # - docker/frontend/.env
      - .env
      - ./opsi-docker/opsi-server/opsi-server.env

services:
  opsi-webgui-frontend-dev:
    env_file: .env # same directory as this file
    build:
      context: ../..
      args:
        HOSTNAME: ${HOSTNAME}
        DEV_USER: ${DEV_USER}
        DEV_GIT_EMAIL: ${DEV_GIT_EMAIL}
        DEV_GIT_NAME: ${DEV_GIT_NAME}
      dockerfile: ./docker/frontend/Dockerfile
    depends_on:
      # created in include part
      - opsi-server
    ports:
      - ${WEBGUI_DEV_PORT}:8888
      - 8889:8889
      - 6006:6006
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    volumes: # pwd is main directory
      - ${PWD}/:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - opsi_data:/data
      - ./files/docker-entrypoint.sh:/docker-entrypoint.sh
    working_dir: /workspace
    entrypoint: ['/docker-entrypoint.sh']
