/**
This file is part of opsi-webgui application.
opsi-webgui is part of the desktop management solution opsi http://www.opsi.org
Copyright (c) uib GmbH <info@uib.de> 2025
All rights reserved.
License: AGPL-3.0
*/

// All available icons: https://icon-sets.iconify.design
// Preferred: bootstrap icons
export const useIcons = () => {
  const icon = {
    add: 'bi:plus',
    admin: 'bi:tools',
    arrowDoubleDown: 'bi:chevron-double-down',
    arrowDoubleLeft: 'bi:chevron-double-left',
    arrowDoubleRight: 'bi:chevron-double-right',
    arrowDoubleUp: 'bi:chevron-double-up',
    arrowDown: 'bi:chevron-down',
    arrowFillDown: 'bi:caret-down-fill',
    arrowFillUp: 'bi:caret-up',
    arrowLeft: 'bi:chevron-left',
    arrowRight: 'bi:chevron-right',
    arrowUp: 'bi:chevron-up',
    bookmark: 'bi:bookmark-fill',
    check: 'bi:check2',
    checkBox: 'material-symbols:check-box-outline',
    client: 'bi:laptop',
    clientReachable: 'bi:link-45deg',
    clone: 'bi:files',
    columns: 'bi:grid-3x3',
    copy: 'bi:copy',
    dash: 'bi:dash',
    delete: 'bi:trash',
    deployClientAgent: 'material-symbols-light:real-estate-agent-outline-sharp',
    depots: 'bi:server',
    download: 'bi:download',
    edit: 'bi:pencil',
    exclamation: 'bi:exclamation',
    filter: 'bi:funnel',
    filterFilled: 'bi:funnel-fill',
    group: 'bi:diagram-2',
    help: 'bi:question-circle',
    info: 'bi:info-circle',
    language: 'bi:globe2',
    loading: 'eos-icons:three-dots-loading',
    log: 'bi:file-earmark-text',
    logout: 'bi:power',
    menu: 'bi:three-dots-vertical',
    navMenu: 'bi:list',
    notify: 'bi:envelope',
    onDemand: 'bi:collection-play',
    product: 'bi:box-seam',
    productActionResult: 'bi:hourglass-bottom',
    productActionResultSuccessful: 'bi:check',
    productInstallationStatusInstalled: 'material-symbols-light:install-desktop-rounded',
    productInstallationStatusUnknown: 'bi:question',
    productsFailedActionResult: 'bi:exclamation',
    productsOutdatedLocal: 'material-symbols-light:deployed-code-history-outline-rounded',
    productsOutdatedNet: 'material-symbols-light:deployed-code-history-rounded',
    quickPanel: 'bi:grid',
    readOnly: 'material-symbols-light:edit-off-outline',
    refresh: 'bi:arrow-repeat',
    rename: 'bi:pencil-square',
    reboot: 'bi:bootstrap-reboot',
    reset: 'bi:arrow-counterclockwise',
    settings: 'bi:gear',
    sort: 'bi:arrows-vertical',
    sortAsc: 'bi:sort-up',
    sortDesc: 'bi:sort-down',
    support: 'bi:headset',
    table: 'bi:table',
    themeLight: 'bi:sun',
    themeDark: 'bi:moon',
    toggleVisibilityLeft: 'bi:chevron-bar-left',
    toggleVisibilityRight: 'bi:chevron-bar-right',
    trackChanges: 'bi:card-checklist',
    tree: 'bi:list-nested',
    unequal: 'mdi:not-equal-variant',
    valueHide: 'bi:eye',
    valueShow: 'bi:eye-slash',
    warning: 'bi:exclamation-triangle',
    x: 'bi:x',
  }
  return { ...icon }
}
