/*
 * This file is part of opsi-webgui application.
 * opsi-webgui is part of the desktop management solution opsi http://www.opsi.org
 * Copyright (c) uib GmbH <info@uib.de> 2026
 * All rights reserved.
 * License: AGPL-3.0
 *
 * useIcons - Centralized icon name mapping for consistent icon usage across the app.
 */
export const icons = {
  // Simple Icons
  windows: 'simple-icons:windows',
  linux: 'simple-icons:linux',
  apple: 'simple-icons:apple',
  // Lucide
  health: 'lucide:activity',
  unequal: 'lucide:equal-not',
  squareCheck: 'lucide:square-check',
  square: 'lucide:square',
  // Heroicons
  productActionResult: 'heroicons:clipboard-document-check',
  productsOutdated: 'heroicons:arrow-up-circle',
  productInstallationStatusUnknown: 'heroicons:question-mark-circle',
  productInstallationStatusInstalled: 'heroicons:check-badge',
  productActionResultSuccessful: 'heroicons:check-circle',
  productsFailedActionResult: 'heroicons:x-circle',
  clientReachable: 'heroicons:wifi',
  client: 'heroicons:computer-desktop',
  server: 'heroicons:server',
  serverStack: 'heroicons:server-stack',
  product: 'heroicons:cube',
  group: 'heroicons:rectangle-group',
  dashboard: 'heroicons:chart-bar-square',
  admin: 'heroicons:wrench-screwdriver',
  support: 'heroicons:lifebuoy',
  whatsNew: 'heroicons:megaphone',
  log: 'heroicons:document-text',
  config: 'heroicons:cog-8-tooth',
  bookmark: 'heroicons:bookmark',
  menu: 'heroicons:bars-3',
  quickPanel: 'heroicons:squares-2x2',
  add: 'heroicons:plus',
  addBold: 'heroicons:plus-16-solid',
  minus: 'heroicons:minus',
  delete: 'heroicons:trash',
  copy: 'heroicons:clipboard-document',
  clone: 'heroicons:document-duplicate',
  onDemand: 'heroicons:bolt',
  deploy: 'heroicons:cloud-arrow-down',
  pencil: 'heroicons:pencil',
  pencilSquare: 'heroicons:pencil-square',
  moreVertical: 'heroicons:ellipsis-vertical',
  check: 'heroicons:check',
  checkCircle: 'heroicons:check-circle',
  x: 'heroicons:x-mark',
  xCircle: 'heroicons:x-circle',
  warning: 'heroicons:exclamation-triangle',
  info: 'heroicons:information-circle',
  chevronDown: 'heroicons:chevron-down',
  chevronLeft: 'heroicons:chevron-left',
  chevronRight: 'heroicons:chevron-right',
  chevronUp: 'heroicons:chevron-up',
  sort: 'heroicons:arrows-up-down',
  sortAsc: 'heroicons:bars-arrow-up',
  sortDesc: 'heroicons:bars-arrow-down',
  back: 'heroicons:arrow-left',
  refresh: 'heroicons:arrow-path',
  reboot: 'lucide:refresh-cw',
  upload: 'heroicons:arrow-up-tray',
  download: 'heroicons:arrow-down-tray',
  filter: 'heroicons:funnel',
  eye: 'heroicons:eye',
  eyeOff: 'heroicons:eye-slash',
  table: 'heroicons:table-cells',
  tableSettings: 'lucide:sliders-horizontal',
  document: 'heroicons:document',
  list: 'heroicons:list-bullet',
  lock: 'heroicons:lock-closed',
  user: 'heroicons:user',
  users: 'heroicons:user-group',
  key: 'heroicons:key',
  logout: 'heroicons:arrow-right-start-on-rectangle',
  language: 'heroicons:globe-alt',
  themeLight: 'heroicons:sun',
  themeDark: 'heroicons:moon',
  clock: 'heroicons:clock',
  notify: 'heroicons:bell',
  shutdown: 'heroicons:power',
} as const

export type IconName = keyof typeof icons
export const useIcons = () => icons
