/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PButton: typeof import('primevue/button')['default']
    PCheckbox: typeof import('primevue/checkbox')['default']
    PDialog: typeof import('primevue/dialog')['default']
    PFloatLabel: typeof import('primevue/floatlabel')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PMultiSelect: typeof import('primevue/multiselect')['default']
    POverlayBadge: typeof import('primevue/overlaybadge')['default']
    PRadioButton: typeof import('primevue/radiobutton')['default']
    PSelect: typeof import('primevue/select')['default']
    PTextarea: typeof import('primevue/textarea')['default']
    PToggleButton: typeof import('primevue/togglebutton')['default']
    PToggleSwitch: typeof import('primevue/toggleswitch')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
