version: '3.8'

services:
  # context is /workspace/docker/
  dev:
    hostname: ${OPSI_HOSTNAME}
    env_file: .env
    privileged: true
    cap_add:
      - SYS_PTRACE
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
      args:
        - USER
        - UID
    volumes:
      - ${PWD}/:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${OPSICONFD_PORT}:${OPSICONFD_PORT}
    environment:
      GF_INSTALL_PLUGINS: grafana-simple-json-datasource
      GF_SECURITY_ADMIN_USER: adminuser
      GF_SECURITY_ADMIN_PASSWORD: adminuser
      MYSQL_ROOT_PASSWORD: opsi
      MYSQL_DATABASE: opsi
      MYSQL_USER: opsi
      MYSQL_PASSWORD: opsi
      MYSQL_HOST: localhost
      OPSICONFD_PORT: ${OPSICONFD_PORT}
      OPSICONFD_STATIC_DIR: /workspace/opsiconfd_data/static
      OPSICONFD_RESTORE_BACKUP_URL=https://binaryindex.uib.gmbh/development/opsi-backups/opsi.acme.corp_4.3.json

      #OPSICONFD_ADDON_DIR: "/usr/lib/opsiconfd/addons"
      OPSICONFD_ADDON_DIR: "/workspace/backend/addon"
    entrypoint: [ '/docker-entrypoint.sh' ]
