FROM mcr.microsoft.com/playwright:v1.15.2-focal AS opsiweb-gui-dev

ARG DOCKER_ENV

ENV DOCKER_ENV=${DOCKER_ENV} \
	# python:
	PYTHONFAULTHANDLER=1 \
	PYTHONUNBUFFERED=1 \
	PYTHONHASHSEED=random \
	# pip:
	PIP_NO_CACHE_DIR=off \
	PIP_DISABLE_PIP_VERSION_CHECK=on \
	PIP_DEFAULT_TIMEOUT=100 \
	# dockerize:
	DOCKERIZE_VERSION=v0.6.1 \
	# opsi
	OPSI_HOSTNAME="opsi.dev.internal" \
	OPSI_REPO=http://obs.uib.local:82/home:/uibmz:/opsi:/4.3:/development/Debian_11/


RUN apt-get update \
	&& apt-get --yes dist-upgrade \
	&& apt-get --yes install \
		cpio \
		vim \
		nano \
		wget \
		sudo \
		git \
		mariadb-client \
		tini \
		psmisc \
		bash-completion


# grafana
RUN wget -q -O - https://packages.grafana.com/gpg.key |  apt-key add - \
	&& echo "deb https://packages.grafana.com/oss/deb stable main" | tee -a /etc/apt/sources.list.d/grafana.list

RUN apt-get update \
	&& apt-get --yes install \
		apt-transport-https \
		software-properties-common \
		grafana

# mysql
RUN apt-get update \
	&& apt-get --yes install \
		mariadb-server

# redis:
RUN  echo "deb $OPSI_REPO /" > /etc/apt/sources.list.d/opsi.list

RUN wget -nv ${OPSI_REPO}Release.key -O Release.key \
	&& apt-key add - < Release.key

RUN apt-get update \
	&& apt-get --yes install \
		redis-tools \
		redis-server \
		redis-timeseries \
		opsi-server-expert \
		debhelper osc zip

RUN wget http://binaryindex.uib.gmbh/development/opsi-dev-tools/linux/x64/opsi-dev-tools_linux_x64_1.14.3.tar.gz \
	&& tar -xf opsi-dev-tools_linux_x64_1.14.3.tar.gz \
	&& ./opsi-dev-tool --self-install

RUN useradd --create-home --home-dir /home/adminuser -s /bin/bash adminuser \
	&& echo "adminuser:adminuser" | chpasswd \
	&& adduser adminuser opsifileadmins \
	&& adduser adminuser opsiadmin


COPY docker/files/ /

WORKDIR /workspace

RUN chown -R pwuser:pwuser /workspace \
	&& adduser pwuser sudo \
	&& echo "pwuser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

RUN chmod +x "/docker-entrypoint.sh"
