version: '3.3'

services:
  opsiweb_dev:
    # image: node:16
    image: mcr.microsoft.com/playwright:v1.6.2-focal
    volumes:
      - ..:/workspace
    working_dir: /workspace/opsiweb
    entrypoint: ["../docker/docker-entrypoint.sh"]
    network_mode: host