version: '3.3'

services:
  opsiweb_dev:
    # image: node:16
    # image: mcr.microsoft.com/playwright:v1.15.2-focal
    hostname: ${OPSI_HOSTNAME}
    env_file:
      ../.env
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ..:/workspace
    working_dir: /workspace
    environment:
      GF_INSTALL_PLUGINS: grafana-simple-json-datasource
      GF_SECURITY_ADMIN_USER: adminuser
      GF_SECURITY_ADMIN_PASSWORD: adminuser
      MYSQL_ROOT_PASSWORD: opsi
      MYSQL_DATABASE: opsi
      MYSQL_USER: opsi
      MYSQL_PASSWORD: opsi
      MYSQL_HOST: localhost
    entrypoint: ["/docker-entrypoint.sh"]
    # network_mode: host