services:
  opsi-webgui-dev:
    hostname: ${OPSI_HOSTNAME}
    env_file: .env
    cap_add:
      - SYS_PTRACE
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        - USER
        - UID
        - ADDON_NAME
        - ADDON_ID
    volumes:
      - ../:/workspace
    ports:
      - '4447:4447' # opsiconfd
      - '3000:3000' # webgui
    environment:
      MYSQL_ROOT_PASSWORD: opsi
      MYSQL_DATABASE: opsi
      MYSQL_USER: opsi
      MYSQL_PASSWORD: opsi
      MYSQL_HOST: localhost
      OPSICONFD_PORT: ${OPSICONFD_PORT}
      OPSICONFD_ADDON_DIRS: '[/var/lib/opsiconfd/addons]'
    entrypoint: ['/entrypoint.sh']
