const { test } = require('@playwright/test')
const { callStoryId } = require('../../uib-components/.utils/playwright/pw-story-call')
const en = require('../../uib-components/locale/en.json')
const de = require('../../uib-components/locale/de.json')

test('Host Attributes', async ({ page }) => {
  await callStoryId(page, 'view-v-config', 'v-config')
  const component = await page.locator('[data-testid="VConfig"]')
  await page.evaluate((val) => { document.querySelector('.hostattr').innerHTML = val }, en['title.hostattr'])
  await page.evaluate((val) => { document.querySelector('.hostId').setAttribute('data-label', val) }, en['table.fields.id'])
  await page.evaluate((val) => { document.querySelector('.type').setAttribute('data-label', val) }, en['table.fields.type'])
  await page.evaluate((val) => { document.querySelector('.description').setAttribute('data-label', val) }, en['table.fields.description'])
  await page.evaluate((val) => { document.querySelector('.notes').setAttribute('data-label', val) }, en['table.fields.notes'])
  await page.evaluate((val) => { document.querySelector('.hwAddr').setAttribute('data-label', val) }, en['table.fields.hwAddr'])
  await page.evaluate((val) => { document.querySelector('.ip').setAttribute('data-label', val) }, en['table.fields.ip'])
  await page.evaluate((val) => { document.querySelector('.inventNum').setAttribute('data-label', val) }, en['table.fields.inventNum'])
  await page.evaluate((val) => { document.querySelector('.created').setAttribute('data-label', val) }, en['table.fields.created'])
  await page.evaluate((val) => { document.querySelector('.lastSeen').setAttribute('data-label', val) }, en['table.fields.lastSeen'])
  await page.evaluate((val) => { document.querySelector('.hostKey').setAttribute('data-label', val) }, en['table.fields.hostKey'])
  await page.evaluate((val) => { document.querySelector('.otp').setAttribute('data-label', val) }, en['table.fields.otp'])
  await page.evaluate((val) => { document.querySelector('.uefi').setAttribute('data-label', val) }, en['table.fields.uefi'])
  await component.screenshot({ path: './screenshots/en/opsiweb_hostattributes.png' })
  await page.evaluate((val) => { document.querySelector('.hostattr').innerHTML = val }, de['title.hostattr'])
  await page.evaluate((val) => { document.querySelector('.type').setAttribute('data-label', val) }, de['table.fields.type'])
  await page.evaluate((val) => { document.querySelector('.description').setAttribute('data-label', val) }, de['table.fields.description'])
  await page.evaluate((val) => { document.querySelector('.notes').setAttribute('data-label', val) }, de['table.fields.notes'])
  await page.evaluate((val) => { document.querySelector('.inventNum').setAttribute('data-label', val) }, de['table.fields.inventNum'])
  await page.evaluate((val) => { document.querySelector('.created').setAttribute('data-label', val) }, de['table.fields.created'])
  await page.evaluate((val) => { document.querySelector('.lastSeen').setAttribute('data-label', val) }, de['table.fields.lastSeen'])
  await page.evaluate((val) => { document.querySelector('.hostKey').setAttribute('data-label', val) }, de['table.fields.hostKey'])
  await page.evaluate((val) => { document.querySelector('.otp').setAttribute('data-label', val) }, de['table.fields.otp'])
  await component.screenshot({ path: './screenshots/de/opsiweb_hostattributes.png' })
})
