export const useIcons = () => {
  const icon = {
    server: 'bi:server',
    client: 'bi:laptop',
    product: 'bi:box-seam',
    group: 'bi:diagram2',
    admin: 'bi:tools',
    support: 'bi:headset',
    settings: 'bi:gear',
    language: 'bi:globe2',
    logout: 'bi:power',
    themelight: 'bi:sun',
    themedark: 'bi:moon',
    trackChanges: 'bi:card-checklist',
    tree: 'bi:list-nested',
    table: 'bi:table',
    navmenu: 'bi:list',
    menu: 'bi:three-dots-vertical',
    quickpanel: 'bi:grid',
    loading: 'eos-icons:three-dots-loading',
    // loading: 'bi:three-dots',
    refetch: 'bi:arrow-clockwise',
    reset: 'bi:arrow-counterclockwise',
    exclamation: 'bi:exclamation',
    pencil: 'bi:pencil',
    x: 'bi:x',
    add: 'bi:plus',
    delete: 'bi:trash',
    help: 'bi:question-circle',
    info: 'bi:info-circle',
    download: 'bi:download',
    check: 'bi:check2',
    dash: 'bi:dash',
    valueShow: 'bi:eye-slash',
    valueHide: 'bi:eye',
    arrowRight: 'bi:chevron-right',
    arrowLeft: 'bi:chevron-left',
    arrowUp: 'bi:chevron-up',
    arrowDown: 'bi:chevron-down',
    arrowDoubleUp: 'bi:chevron-double-up',
    arrowDoubleDown: 'bi:chevron-double-down',
    arrowDoubleLeft: 'bi:chevron-double-left',
    arrowDoubleRight: 'bi:chevron-double-right',
    arrowFillUp: 'bi:caret-up',
    arrowFillDown: 'bi:caret-down-fill',
    log: 'bi:file-earmark-text',
    clientReachable: 'bi:link45deg',
    ondemand: 'bi:collection-play',
    message: 'bi:envelope',
    reboot: 'bi:bootstrap-reboot',
    productInstallationStatusUnknown: 'bi:question',
    productActionResult: 'bi:hourglass-bottom',
    productsFailedActionResult: 'bi:exclamation',
    productActionResultSuccessful: 'bi:check',
    productsOutdated: 'bi:cloud-arrow-down',
    sort: 'bi:sort-up',
    sortDesc: 'bi:sort-down',
    columns: 'bi:grid3x3',
    filter: 'bi:funnel',
    clear: 'bi:brush',
    refresh: 'bi:arrow-repeat',
    _stackedIcons: {
      readonly: [
        { icon: 'bi:pencil', scale: '0.55' },
        { icon: 'bi:slash-circle', attr: { 'flip-h': true, variant: 'danger' } }
      ]
    }
  }
  return { ...icon }
 }