import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

test.describe('accessibility', () => {
  test('topbar', async ({ page }) => {
    const accessibilityScanResults = await new AxeBuilder({ page })
      .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
      .include('[data-testid="BarBTop"]')
      .analyze()
    expect(accessibilityScanResults.violations).toEqual([])
  })

  test('sidebar', async ({ page }) => {
    const accessibilityScanResults = await new AxeBuilder({ page })
      .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
      .include('[data-testid="BarBSide"]')
      .analyze()
    expect(accessibilityScanResults.violations).toEqual([])
  })

  test('clients', async ({ page }) => {
    const accessibilityScanResults = await new AxeBuilder({ page })
      .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
      .include('[data-testid="VClients"]')
      .analyze()
    expect(accessibilityScanResults.violations).toEqual([])
  })
  test('clients - creation', async ({ page }) => {
    await page.click('[data-testid="NICollapsible-title.clients"]')
    await page.click('[data-testid="NICollapsible-submenu-title.clientstitle.addNew"]')
    await new Promise((resolve) => setTimeout(resolve, 4000))
    await expect(page).toHaveURL('/addons/webgui/app/clients/creation')
    const accessibilityScanResults = await new AxeBuilder({ page })
      .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
      .include('[data-testid="VClientCreation"]')
      .analyze()
    expect(accessibilityScanResults.violations).toEqual([])
  })
  test('clients - config with active Atrributes tab', async ({ page }) => {
    await page.click('[data-testid="NICollapsible-title.clients"]')
    await page.click('[data-testid="NICollapsible-submenu-title.clientstitle.config"]')
    await new Promise((resolve) => setTimeout(resolve, 4000))
    await expect(page).toHaveURL('/addons/webgui/app/clients/config')
    const accessibilityScanResults = await new AxeBuilder({ page })
      .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
      .include('[data-testid="VConfig"]')
      .analyze()
    expect(accessibilityScanResults.violations).toEqual([])
  })
  test('clients - parameters', async ({ page }) => {
    await page.click('[data-testid="NICollapsible-title.clients"]')
    await page.click('[data-testid="NICollapsible-submenu-title.clientstitle.config"]')
    await expect(page).toHaveURL('/addons/webgui/app/clients/config')
    await new Promise((resolve) => setTimeout(resolve, 4000))
    await page.click('[data-testid="Parameters"]')
    await new Promise((resolve) => setTimeout(resolve, 4000))
    const accessibilityScanResults = await new AxeBuilder({ page })
      .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
      .include('[data-testid="GHostParam"]')
      .analyze()
    expect(accessibilityScanResults.violations).toEqual([])
  })
  test('groups with a selected group', async ({ page }) => {
    await page.click('[data-testid="NIItem-title.groups"]')
    await expect(page).toHaveURL('/addons/webgui/app/groups/')
    await new Promise((resolve) => setTimeout(resolve, 1000))
    await page.getByText('clientdirectory').click()
    await new Promise((resolve) => setTimeout(resolve, 1000))
    const accessibilityScanResults = await new AxeBuilder({ page })
      .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
      .include('[data-testid="VGroups"]')
      .analyze()
    expect(accessibilityScanResults.violations).toEqual([])
  })
  test('products', async ({ page }) => {
    await page.click('[data-testid="NIItem-title.products"]')
    await expect(page).toHaveURL('/addons/webgui/app/products/LocalbootProducts')
    const accessibilityScanResults = await new AxeBuilder({ page })
      .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
      .include('[data-testid="VProducts"]')
      .analyze()
    expect(accessibilityScanResults.violations).toEqual([])
  })
})
